apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: ${CERTIFICATE_AUTHORITY_DATA}
      server: ${SERVER_URL}
    name: ${CLUSTER_NAME}
contexts:
  - context:
      cluster: ${CLUSTER_NAME}
      user: ${USER_NAME}
    name: ${CONTEXT_NAME}
current-context: ${CONTEXT_NAME}
kind: Config
preferences: {}
users:
  - name: ${USER_NAME}
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - token
          - --clusterUuid
          - ${CLUSTER_UUID}
          - --region
          - ${REGION}
        command: ${COMMAND}
        env: null
        provideClusterInfo: false