apiVersion: v1
kind: Pod
metadata:
  name: sample-app-pod
  labels:
    app: sample-app
spec:
  imagePullSecrets:
    - name: ncloud-registry-secret
  containers:
    - name: sample-app
      image: action.kr.ncr.ntruss.com/node-kubernetes-sampl
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
spec:
  type: ClusterIP
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000